### ISSUE TITLE
Prompt format for LLaMa

### ISSUE THREAD

**Issue by LeeShiyang** [declare-lab/flan-eval#2]
Hi all, thank you for introducing this nice work. I have a question regarding prompt format for Alpaca-like models. Alpaca-like models have a [specific format ](https://github.com/tatsu-lab/stanford_alpaca/blob/65512697dc67779a6e53c267488aba0ec4d7c02a/train.py#L31) during training and it looks like the provided evaluation scripts do not take this into account (correct me if I am wrong). Have you considered to taking this into account? For example, add one additional argument for a specific format in the evaluation script. Thank you.

**Comment by chiayewken** [comment]
Hi, thanks for raising this issue. The [current code](https://github.com/declare-lab/flan-eval/blob/8102636a558d7d8bc4eadb3f27d4628d72d08c71/modeling.py#L116) supports the Alpaca instruction template if you use the `--use_template` flag. However, our initial testing showed that it did not make much difference for few-shot prompting and we actually had slightly better results without the template.

**Comment by LeeShiyang** [comment]
Thank you for your reply.
