### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by passaglia** [declare-lab/flan-eval#5]
Thanks for sharing this wonderful evals code. To facilitate use, please consider adding an open source license to the project. Without a license, [no one can use your code](http://opensource.stackexchange.com/q/1720/775).

**Comment by chiayewken** [comment]
Hi, thanks for raising this issue! We have added the apache 2.0 license

**Comment by passaglia** [comment]
Thank you @chiayewken :rocket: :rocket: !!
